### ISSUE TITLE
ImportError: cannot import name 'six' from 'pkg_resources.extern' (/usr/lib/python3/dist-packages/pkg_resources/extern/__init__.py)

### ISSUE THREAD

**Issue by likecv** [Yiming-M/CLIP-EBC#17]
python3 test_nwpu.py     --model clip_vit_b_16 --input_size 224 --reduction 8 --truncation 4 --anchor_points average --prompt_type word     --num_vpt 32 --vpt_drop 0.0 --sliding_window --stride 224     --weight_path models_temp/best_rmse.pth --device cuda:0
Traceback (most recent call last):
  File "/home/lk/test/clip_ebc/CLIP-EBC/test_nwpu.py", line 9, in <module>
    from models import get_model
  File "/home/lk/test/clip_ebc/CLIP-EBC/models/__init__.py", line 4, in <module>
    from .clip import _clip_ebc, CLIP_EBC
  File "/home/lk/test/clip_ebc/CLIP-EBC/models/clip/__init__.py", line 1, in <module>
    from .model import CLIP_EBC, _clip_ebc
  File "/home/lk/test/clip_ebc/CLIP-EBC/models/clip/model.py", line 9, in <module>
    from . import _clip
  File "/home/lk/test/clip_ebc/CLIP-EBC/models/clip/_clip/__init__.py", line 6, in <module>
    from .utils import tokenize, transform
  File "/home/lk/test/clip_ebc/CLIP-EBC/models/clip/_clip/utils.py", line 6, in <module>
    from pkg_resources import packaging
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 50, in <module>
    from pkg_resources.extern import six
ImportError: cannot import name 'six' from 'pkg_resources.extern' (/usr/lib/python3/dist-packages/pkg_resources/extern/__init__.py)

**Comment by Yiming-M** [comment]
Hi. This issue comes from not installing and activating the required conda environment.
