### ISSUE TITLE
TypeError: RandomResizedCrop.__call__() missing 1 required positional argument: 'label'

### ISSUE THREAD

**Issue by 3555367879** [Yiming-M/CLIP-EBC#2]
Hello, I encountered the following error while running the code:
```
Traceback (most recent call last):
  File "/mnt/C/CrowdCounting/CLIP-EBC-main/trainer.py", line 215, in <module>
    main()
  File "/mnt/C/CrowdCounting/CLIP-EBC-main/trainer.py", line 211, in main
    run(0, 1, args)
  File "/mnt/C/CrowdCounting/CLIP-EBC-main/trainer.py", line 146, in run
    model, optimizer, loss_info = train(model, train_loader, loss_fn, optimizer, device, local_rank, nprocs)
  File "/mnt/C/CrowdCounting/CLIP-EBC-main/train.py", line 28, in train
    for image, target_points, target_density in data_iter:
  File "/mnt/A/.conda/envs/CLIP-EBC-main/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/mnt/A/.conda/envs/CLIP-EBC-main/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/mnt/A/.conda/envs/CLIP-EBC-main/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 678, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/mnt/A/.conda/envs/CLIP-EBC-main/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/A/.conda/envs/CLIP-EBC-main/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/C/CrowdCounting/CLIP-EBC-main/datasets/crowd.py", line 171, in __getitem__
    images_labels = [self.transforms(image.clone(), label.clone()) for _ in range(self.num_crops)]
  File "/mnt/C/CrowdCounting/CLIP-EBC-main/datasets/crowd.py", line 171, in <listcomp>
    images_labels = [self.transforms(image.clone(), label.clone()) for _ in range(self.num_crops)]
  File "/mnt/A/.conda/envs/CLIP-EBC-main/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/A/.conda/envs/CLIP-EBC-main/lib/python3.10/site-packages/torchvision/transforms/v2/_container.py", line 51, in forward
    sample = transform(sample)
TypeError: RandomResizedCrop.__call__() missing 1 required positional argument: 'label'
```
Has anyone encountered the same problem? Are there any solutions available?

**Comment by Yiming-M** [comment]
Hi @3555367879 , 

I have tested the code again, but I am not seeing this error. Could you please double check whether you are using the transform functions defined in [`datasets.transforms.py`](https://github.com/Yiming-M/CLIP-EBC/blob/main/datasets/transforms.py)? Please do not use any transforms officially implemented by PyTorch, as they don't correspondingly transform the dot annotations.

Looking forward to your reply.

Many thanks,
Yiming

**Comment by Yiming-M** [comment]
Hi @3555367879 ,

Thanks for letting me know. Since this issue has been resolved, I am going to close it. But feel free to create GitHub issues when you see other problems.

Many thanks,
Yiming
