### ISSUE TITLE
评估

### ISSUE THREAD

**Issue by susu-source** [Yiming-M/CLIP-EBC#20]
您好！

我测试clip_vit_b_16在sha数据集上的效果的时候，代码报这样的错误
Testing a trained model on the SHA test set.
model          :        clip_vit_b_16
input_size     :        224
reduction      :        8
regression     :        False
truncation     :        4
anchor_points  :        average
prompt_type    :        word
granularity    :        fine
num_vpt        :        32
vpt_drop       :        0.0
shallow_vpt    :        False
weight_path    :        ./checkpoints/sha/clip_vit_b_16_word_224_8_4_fine_1.0_dmcount/best_mae_0.pth
sliding_window :        True
stride         :        224
window_size    :        224
resize_to_multiple:     False
zero_pad_to_multiple:   False
device         :        cuda
num_workers    :        4
Missing keys: []
Unexpected keys: ['proj']
All keys matched successfully.
Initialized model with text prompts: ['There is no person.', 'There is one person.', 'There are two people.', 'There are three people.', 'There are more than four people.']
Testing on SHA:   0%|          | 0/182 [00:00<?, ?it/s]D:\anaconda\envs\CLIP-EBC-main\Lib\site-packages\torch\nn\functional.py:5476: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  attn_output = scaled_dot_product_attention(q, k, v, attn_mask, dropout_p, is_causal)
Testing on SHA:  18%|▒▒▒▒        | 33/182 [00:05<00:25,  5.93it/s]
Traceback (most recent call last):
  File "D:\CLIP-EBC-main\test_sha.py", line 167, in <module>
    main(args)
  File "D:\CLIP-EBC-main\test_sha.py", line 113, in main
    pred_density = sliding_window_predict(model, image, window_size, stride)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CLIP-EBC-main\utils\eval_utils.py", line 95, in sliding_window_predict
    pred_map[:, (x_start // reduction): (x_end // reduction), (y_start // reduction): (y_end // reduction)] += preds[idx, :, :, :]
ValueError: operands could not be broadcast together with shapes (1,3,28) (1,2,28) (1,3,28)

请问这种情况该怎么修改呢

非常感谢

**Comment by Yiming-M** [comment]
Hi, 

It seems that the `test_sha.py` file is not from our repo so we are unable to locate and solve this bug. Sorry for the inconvenience.

Many thanks,
Yiming

**Comment by bit-scientist** [comment]
Could you also release the evaluation code snippets for other datasets except **NWPU Test**? Those would be for QNRF, SHA and SHA test sets. Thanks.
