### ISSUE TITLE
Use pretrained model as initial weight

### ISSUE THREAD

**Issue by ml-cv-developer** [Yiming-M/CLIP-EBC#4]
I am trying to use a pretrained model in here as initial weight.
https://drive.google.com/drive/folders/1hEHRsyOxvtbnq8UR0iXnQ7kcKO7aaYVM?usp=sharing
But got this error.
```
Traceback (most recent call last):
  File "/home/viso/crowd_clip_ebc/CLIP-EBC/trainer.py", line 215, in <module>
    main()
  File "/home/viso/crowd_clip_ebc/CLIP-EBC/trainer.py", line 211, in main
    run(0, 1, args)
  File "/home/viso/crowd_clip_ebc/CLIP-EBC/trainer.py", line 123, in run
    model, optimizer, scheduler, start_epoch, loss_info, hist_scores, best_scores = load_checkpoint(args, model, optimizer, scheduler)
  File "/home/viso/crowd_clip_ebc/CLIP-EBC/utils/train_utils.py", line 111, in load_checkpoint
    model.load_state_dict(ckpt["model_state_dict"])
KeyError: 'model_state_dict'
```
Can you please give me a guide how I can use pre-trained weights as initial weight of the training?
Best regards,

**Comment by Yiming-M** [comment]
Hi @ml-cv-developer ,

We haven't heard from you for two weeks, so we guess that this issue has been solved. Please feel free to re-open it if this is not the case.

Many thanks,
Yiming
